/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package EstabelecimentoUI;

import controladoras.EstabelecimentoJpaController;
import controladoras.UtilizadoresJpaController;
import entidades.Estabelecimento;
import entidades.Utilizadores;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author _aphie_d
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        acncorarEstComboBox();

    }

    UtilizadoresJpaController uc = new UtilizadoresJpaController();
    List<Utilizadores> Ut = uc.findUtilizadoresEntities();
    Utilizadores U = new Utilizadores();
    int id = 0;

    private void acncorarEstComboBox() {
        EstabelecimentoJpaController cc = new EstabelecimentoJpaController();
        List<Estabelecimento> E = cc.findEstabelecimentoEntities();
        List<String> estabelecimento = new ArrayList<>();

        for (int i = 0; i < E.size(); i++) {
            estabelecimento.add(E.get(i).getNomeEstabelecimento());
        }

        Object[] estabelecimentosArray = estabelecimento.toArray();
        DefaultComboBoxModel model = new DefaultComboBoxModel(estabelecimentosArray);
        EstjComboBox.setModel(model);
    }

    private Estabelecimento getEst() {
        EstabelecimentoJpaController cc = new EstabelecimentoJpaController();
        List<Estabelecimento> E = cc.findEstabelecimentoEntities();

        for (Estabelecimento E1 : E) {
            if (E1.getNomeEstabelecimento().trim().equalsIgnoreCase(EstjComboBox.getSelectedItem().toString().trim())) {
                return E1;
            }
        }
        return null;
    }

    public boolean userExists() {
        String codigo = LoginCodigoTxtField.getText();
        String password = LoginSenhaTxtField.getText();

        for (int i = 0; i < Ut.size(); i++) {
            if (Ut.get(i).getCodigoUtilizador().equals(codigo.trim()) && Ut.get(i).getSenhaUtilizador().equals(password.trim())) {
                id = Ut.get(i).getIdUtilizador();
                U = Ut.get(i);
                return true;
            }
        }
        return false;
    }

//    private void acncorarEstComboBox() {
//        EstabelecimentoJpaController ec = new EstabelecimentoJpaController();
//        List<Estabelecimento> E = ec.findEstabelecimentoEntities();
//        List<String> estabelecimentos = new ArrayList<>();
//
//        for (int i = 0; i < E.size(); i++) {
//            estabelecimentos.add(E.get(i).getCodigoEstabelecimento());
//        }
//
//        Object[] estabelecimentosArray = estabelecimentos.toArray();
//        DefaultComboBoxModel model = new DefaultComboBoxModel(estabelecimentosArray);
//        jComboBox1.setModel(model);
//    }
    public boolean isAdmin() {
        U = uc.findUtilizadores(id);
        if (!U.getFuncaoUtilizador().equalsIgnoreCase("admin")) {
            return false;
        }
        return true;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LoginPainel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        LoginBtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        CancelBtn = new javax.swing.JButton();
        LoginSenhaTxtField = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        LoginCodigoTxtField = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        EstjComboBox = new javax.swing.JComboBox<>();
        NewEstjButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel4.setText("Senha:");

        LoginBtn.setText("Entrar");
        LoginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginBtnActionPerformed(evt);
            }
        });

        jLabel3.setText("Acesso:");

        CancelBtn.setText("Cancelar");
        CancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelBtnActionPerformed(evt);
            }
        });

        LoginSenhaTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginSenhaTxtFieldActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Cocogoose", 1, 24)); // NOI18N
        jLabel1.setText("Loja 1");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Estabelecimentos"));

        EstjComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        NewEstjButton.setText("Novo");
        NewEstjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewEstjButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(EstjComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(NewEstjButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EstjComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NewEstjButton))
                .addGap(0, 45, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout LoginPainelLayout = new javax.swing.GroupLayout(LoginPainel);
        LoginPainel.setLayout(LoginPainelLayout);
        LoginPainelLayout.setHorizontalGroup(
            LoginPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoginPainelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(LoginPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(LoginPainelLayout.createSequentialGroup()
                        .addComponent(LoginBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49)
                        .addComponent(CancelBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jSeparator1)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(LoginPainelLayout.createSequentialGroup()
                        .addGroup(LoginPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(LoginPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LoginCodigoTxtField)
                            .addComponent(LoginSenhaTxtField))))
                .addContainerGap())
            .addGroup(LoginPainelLayout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        LoginPainelLayout.setVerticalGroup(
            LoginPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LoginPainelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(LoginPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LoginCodigoTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(LoginPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LoginSenhaTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(LoginPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CancelBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LoginBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE))
                .addContainerGap())
        );

        LoginPainelLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {LoginCodigoTxtField, LoginSenhaTxtField, jLabel3, jLabel4});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LoginPainel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(LoginPainel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LoginSenhaTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginSenhaTxtFieldActionPerformed

        // TODO add your handling code here:
    }//GEN-LAST:event_LoginSenhaTxtFieldActionPerformed

    private void CancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelBtnActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_CancelBtnActionPerformed

    private void LoginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginBtnActionPerformed
        // TODO add your handling code here:
        String codigo = LoginCodigoTxtField.getText();
        String password = LoginSenhaTxtField.getText();

        if (codigo.equals("") || password.equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Preencha todos os campos!");
        } else if (userExists()) {
            if (getEst().getUtilizadoresList().contains(U)) {
                if (isAdmin()) {
                    Admin admin = new Admin(U, U.getEstabelecimentoId());
                    admin.setVisible(true);
                    dispose();
                } else {
                    User user = new User();
                    user.setVisible(true);
                    dispose();
                }
            } else {
                JOptionPane.showMessageDialog(rootPane, "Nao encontramos o seu utilizador em " + getEst().getNomeEstabelecimento());
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "Codigo ou Senha Incorrecta!");
        }
    }//GEN-LAST:event_LoginBtnActionPerformed

    private void NewEstjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewEstjButtonActionPerformed
        // TODO add your handling code here:
        NovoEstabelecimento ne = new NovoEstabelecimento();
        ne.setVisible(true);
        dispose();
    }//GEN-LAST:event_NewEstjButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CancelBtn;
    private javax.swing.JComboBox<String> EstjComboBox;
    private javax.swing.JButton LoginBtn;
    private javax.swing.JTextField LoginCodigoTxtField;
    private javax.swing.JPanel LoginPainel;
    private javax.swing.JPasswordField LoginSenhaTxtField;
    private javax.swing.JButton NewEstjButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
