/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package EstabelecimentoUI;

import controladoras.UtilizadoresJpaController;
import entidades.Estabelecimento;
import entidades.Utilizadores;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author APHIED
 */
public class NovoUtilizador extends javax.swing.JFrame {

    private Estabelecimento estActual;

    /**
     * Creates new form NovoUtilizador
     *
     * @param estabelecimento
     */
    public NovoUtilizador(Estabelecimento estabelecimento) {
        initComponents();
        estActual = estabelecimento;
        ancorarComboUser();
    }

    private void ancorarComboUser() {
        List<String> funcaoUser = new ArrayList<>();
        funcaoUser.add("Sales");
        funcaoUser.add("Admin");

        Object[] funcaoArray = funcaoUser.toArray();
        DefaultComboBoxModel model = new DefaultComboBoxModel(funcaoArray);
        AdminFuncaoComboBox.setModel(model);
    }

    public void cadastrarUser() {
        UtilizadoresJpaController uc = new UtilizadoresJpaController();
        Utilizadores u = new Utilizadores();

        try {
            u.setNomeUtlizador(AdminNomeUserTxtField.getText());
            u.setCodigoUtilizador(AdminCodUserTxtField.getText());
            u.setFuncaoUtilizador(AdminFuncaoComboBox.getSelectedItem().toString());
            u.setSenhaUtilizador(AdminSenhaTxtField.getText());
            u.setEstabelecimentoId(estActual);
            u.setCodigoEstabelecimento(estActual.getCodigoEstabelecimento());
            u.setActivoUtilizador(true);
            uc.create(u);
            JOptionPane.showMessageDialog(rootPane, "Utilizador Adicionado com sucesso!");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Nao foi possivel adicionar utilizador! Erro: " + e.getMessage());
        }
        Login login = new Login();
        login.setVisible(true);
        dispose();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        AdminAddUserjButton = new javax.swing.JButton();
        AdminNomeUserTxtField = new javax.swing.JTextField();
        AdminCodUserTxtField = new javax.swing.JTextField();
        AdminSenhaTxtField = new javax.swing.JPasswordField();
        AdminFuncaoComboBox = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Novo Utilizador");

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel16.setText("Nome Completo:");

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel17.setText("Codigo Utilizador:");

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel19.setText("Senha");

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel22.setText("Funcao: ");

        AdminAddUserjButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        AdminAddUserjButton.setText("Adicionar");
        AdminAddUserjButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AdminAddUserjButtonMouseClicked(evt);
            }
        });
        AdminAddUserjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdminAddUserjButtonActionPerformed(evt);
            }
        });

        AdminNomeUserTxtField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        AdminNomeUserTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdminNomeUserTxtFieldActionPerformed(evt);
            }
        });

        AdminCodUserTxtField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        AdminSenhaTxtField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        AdminFuncaoComboBox.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        AdminFuncaoComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        AdminFuncaoComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdminFuncaoComboBoxActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setText("Cancelar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 8, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel22, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel19, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.LEADING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(AdminNomeUserTxtField)
                                    .addComponent(AdminCodUserTxtField)
                                    .addComponent(AdminFuncaoComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(AdminSenhaTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(AdminAddUserjButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(155, 155, 155)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {AdminAddUserjButton, jButton1});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(AdminNomeUserTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(AdminCodUserTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(AdminSenhaTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(AdminFuncaoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AdminAddUserjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {AdminAddUserjButton, jButton1});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AdminNomeUserTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdminNomeUserTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AdminNomeUserTxtFieldActionPerformed

    private void AdminFuncaoComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdminFuncaoComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AdminFuncaoComboBoxActionPerformed

    private void AdminAddUserjButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AdminAddUserjButtonMouseClicked
        // TODO add your handling code here:
        String nome = AdminNomeUserTxtField.getText();
        String cod = AdminCodUserTxtField.getText();
        String funcao = AdminFuncaoComboBox.getSelectedItem().toString();
        String senha = AdminSenhaTxtField.getText();

        if (nome.equals("") || cod.equals("") || funcao.equals("") || senha.equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Preencha todos os campos!");
        } else {
            cadastrarUser();
        }
    }//GEN-LAST:event_AdminAddUserjButtonMouseClicked

    private void AdminAddUserjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdminAddUserjButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AdminAddUserjButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

//    public static void main(String[] args) {
//        NovoUtilizador nu = new NovoUtilizador();
//        nu.setVisible(true);
//    } 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AdminAddUserjButton;
    private javax.swing.JTextField AdminCodUserTxtField;
    private javax.swing.JComboBox<String> AdminFuncaoComboBox;
    private javax.swing.JTextField AdminNomeUserTxtField;
    private javax.swing.JPasswordField AdminSenhaTxtField;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
