/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package EstabelecimentoUI;

import controladoras.EstabelecimentoJpaController;
import controladoras.UtilizadoresJpaController;
import entidades.Estabelecimento;
import entidades.Utilizadores;
import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.ws.rs.client.ClientBuilder;
import javax.ws.rs.client.Entity;
import javax.ws.rs.client.WebTarget;
import javax.ws.rs.core.MediaType;
import javax.ws.rs.core.Response;

/**
 *
 * @author Sunil
 */
public class NovoEstabelecimento extends javax.swing.JFrame {

    /**
     * Creates new form NovoEstabelecimento
     */
    public NovoEstabelecimento() {
        initComponents();
        ancorarComboTipoEst();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        AddEstjPanel = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        AdminNomeEstbjTextField = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        AdminCodEstbjTextField = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        AdminEmailEstbjTextField = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        AdminTelEstbjTextField = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        AdminCisadeEstbjTextField = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        AdminCodPostalEstbjTextField = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        AdminIvaEstbjTextField = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        AdminEstadoEstbjTextField = new javax.swing.JTextField();
        AdminTipoEstjComboBox = new javax.swing.JComboBox<>();
        AdminAddEstjButton = new javax.swing.JButton();
        ExitjButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        AddEstjPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Detalhes do Estabelecimento", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N

        jLabel21.setText("Nome do Estabelecimento:");

        jLabel23.setText("Codigo do Estabelecimento:");

        AdminCodEstbjTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdminCodEstbjTextFieldActionPerformed(evt);
            }
        });

        jLabel24.setText("Email:");

        jLabel25.setText("Telefone:");

        jLabel26.setText("Cidade:");

        jLabel27.setText("Codigo Postal: ");

        jLabel28.setText("IVA:");

        jLabel29.setText("Tipo de estabelecimento:");

        jLabel30.setText("Estado:");

        AdminTipoEstjComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        AdminAddEstjButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        AdminAddEstjButton.setText("Adicionar");
        AdminAddEstjButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AdminAddEstjButtonMouseClicked(evt);
            }
        });
        AdminAddEstjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdminAddEstjButtonActionPerformed(evt);
            }
        });

        ExitjButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ExitjButton.setText("Sair");
        ExitjButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ExitjButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout AddEstjPanelLayout = new javax.swing.GroupLayout(AddEstjPanel);
        AddEstjPanel.setLayout(AddEstjPanelLayout);
        AddEstjPanelLayout.setHorizontalGroup(
            AddEstjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddEstjPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AddEstjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AddEstjPanelLayout.createSequentialGroup()
                        .addGroup(AddEstjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(AddEstjPanelLayout.createSequentialGroup()
                                .addComponent(jLabel28)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(AddEstjPanelLayout.createSequentialGroup()
                                .addGroup(AddEstjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel26)
                                    .addComponent(jLabel24))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 299, Short.MAX_VALUE)))
                        .addGroup(AddEstjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AddEstjPanelLayout.createSequentialGroup()
                                .addComponent(jLabel30)
                                .addGap(18, 18, 18)
                                .addComponent(AdminEstadoEstbjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(AddEstjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(AddEstjPanelLayout.createSequentialGroup()
                                    .addComponent(jLabel25)
                                    .addGap(18, 18, 18)
                                    .addComponent(AdminTelEstbjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(AddEstjPanelLayout.createSequentialGroup()
                                    .addComponent(jLabel27)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(AdminCodPostalEstbjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(AddEstjPanelLayout.createSequentialGroup()
                        .addGroup(AddEstjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel23)
                            .addComponent(jLabel21))
                        .addGap(18, 18, 18)
                        .addGroup(AddEstjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(AdminNomeEstbjTextField)
                            .addGroup(AddEstjPanelLayout.createSequentialGroup()
                                .addComponent(AdminCodEstbjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel29)
                                .addGap(18, 18, 18)
                                .addComponent(AdminTipoEstjComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AddEstjPanelLayout.createSequentialGroup()
                        .addGap(0, 89, Short.MAX_VALUE)
                        .addGroup(AddEstjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AddEstjPanelLayout.createSequentialGroup()
                                .addGroup(AddEstjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(AddEstjPanelLayout.createSequentialGroup()
                                        .addGap(2, 2, 2)
                                        .addComponent(AdminIvaEstbjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(AddEstjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(AddEstjPanelLayout.createSequentialGroup()
                                            .addGap(1, 1, 1)
                                            .addComponent(AdminCisadeEstbjTextField))
                                        .addComponent(AdminEmailEstbjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(387, 387, 387))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AddEstjPanelLayout.createSequentialGroup()
                                .addComponent(AdminAddEstjButton)
                                .addGap(18, 18, 18)
                                .addComponent(ExitjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(254, 254, 254)))))
                .addContainerGap())
        );
        AddEstjPanelLayout.setVerticalGroup(
            AddEstjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddEstjPanelLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(AddEstjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(AdminNomeEstbjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(AddEstjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(AdminCodEstbjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel29)
                    .addComponent(AdminTipoEstjComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(AddEstjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(AddEstjPanelLayout.createSequentialGroup()
                        .addGroup(AddEstjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel25)
                            .addComponent(AdminTelEstbjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(AddEstjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel27)
                            .addComponent(AdminCodPostalEstbjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(AddEstjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel30)
                            .addComponent(AdminEstadoEstbjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(AddEstjPanelLayout.createSequentialGroup()
                        .addGroup(AddEstjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel24)
                            .addComponent(AdminEmailEstbjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(AddEstjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel26)
                            .addComponent(AdminCisadeEstbjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(AddEstjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(AdminIvaEstbjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel28))))
                .addGap(18, 18, 18)
                .addGroup(AddEstjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(AdminAddEstjButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ExitjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 726, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(AddEstjPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 306, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(AddEstjPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ancorarComboTipoEst() {
        List<String> tipoEst = new ArrayList<>();
        tipoEst.add("Supermercado ou Mercearia");
        tipoEst.add("Papelaria ou Grafica");
        tipoEst.add("Restaurante ou Padaria");
        tipoEst.add("Loja de Diversos");
        tipoEst.add("Livraria");
        tipoEst.add("Ferragem");
        tipoEst.add("Farmacia");
        tipoEst.add("Informal");
        tipoEst.add("Armazem");
        tipoEst.add("Bar");

        Object[] tipoArray = tipoEst.toArray();
        DefaultComboBoxModel model = new DefaultComboBoxModel(tipoArray);
        AdminTipoEstjComboBox.setModel(model);
    }

    private void registrarEstabelecimento() {
        EstabelecimentoJpaController ec = new EstabelecimentoJpaController();
        Estabelecimento e = new Estabelecimento();

        e.setNomeEstabelecimento(AdminNomeEstbjTextField.getText());
        e.setCodigoEstabelecimento(AdminCodEstbjTextField.getText());
        e.setEmailEstabelecimento(AdminEmailEstbjTextField.getText());
        e.setTelefoneEstabelecimento(AdminTelEstbjTextField.getText());
        e.setCidadeEstabelecimento(AdminCisadeEstbjTextField.getText());
        e.setCodigoPostal(AdminCodPostalEstbjTextField.getText());
        e.setIvaEstabelecimento(BigInteger.valueOf(Integer.valueOf(AdminIvaEstbjTextField.getText()).longValue()));
        e.setTipoEstabelecimento(AdminTipoEstjComboBox.getSelectedItem().toString());
        e.setActivo(true);

        try {
            ec.create(e);
            JOptionPane.showMessageDialog(rootPane, "Estabelecimento adicionado com sucesso!");

            try {
                javax.ws.rs.client.Client client;
                client = ClientBuilder.newClient();
                String BASE_URI = "http://localhost:8086/Comparador/webresources";
                WebTarget webTarget = client.target(BASE_URI).path("estabelecimento");

                Response response = webTarget
                        .request()
                        .accept(MediaType.APPLICATION_XML)
                        .post(Entity.entity(e, MediaType.APPLICATION_XML));

                System.out.println(response);
                client.close();
            } catch (Exception exp) {
                JOptionPane.showMessageDialog(rootPane, "Nao foi possivel adicionar o Estabelecimento online! | " + exp.getStackTrace());
            }

            NovoUtilizador nu = new NovoUtilizador(e);
            nu.setVisible(true);
            dispose();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, "Nao foi possivel adicionar um novo estabelecimento!" + ex.getMessage());
        }
    }


    private void AdminCodEstbjTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdminCodEstbjTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AdminCodEstbjTextFieldActionPerformed

    private void AdminAddEstjButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AdminAddEstjButtonMouseClicked
        // TODO add your handling code here:
        if (AdminCisadeEstbjTextField.getText().isEmpty() || AdminCodEstbjTextField.getText().isEmpty() || AdminCodPostalEstbjTextField.getText().isEmpty() || AdminEmailEstbjTextField.getText().isEmpty() || AdminEstadoEstbjTextField.getText().isEmpty() || AdminIvaEstbjTextField.getText().isEmpty() || AdminNomeEstbjTextField.getText().isEmpty() || AdminTelEstbjTextField.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Prencha todos os campos!");
        } else {
            registrarEstabelecimento();
        }

    }//GEN-LAST:event_AdminAddEstjButtonMouseClicked

    private void AdminAddEstjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdminAddEstjButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AdminAddEstjButtonActionPerformed

    private void ExitjButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitjButtonMouseClicked
        // TODO add your handling code here:
        Login login = new Login();
        login.setVisible(true);
        dispose();
    }//GEN-LAST:event_ExitjButtonMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AddEstjPanel;
    private javax.swing.JButton AdminAddEstjButton;
    private javax.swing.JTextField AdminCisadeEstbjTextField;
    private javax.swing.JTextField AdminCodEstbjTextField;
    private javax.swing.JTextField AdminCodPostalEstbjTextField;
    private javax.swing.JTextField AdminEmailEstbjTextField;
    private javax.swing.JTextField AdminEstadoEstbjTextField;
    private javax.swing.JTextField AdminIvaEstbjTextField;
    private javax.swing.JTextField AdminNomeEstbjTextField;
    private javax.swing.JTextField AdminTelEstbjTextField;
    private javax.swing.JComboBox<String> AdminTipoEstjComboBox;
    private javax.swing.JButton ExitjButton;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
